FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy all files into a 'backend' folder inside /app
COPY . ./backend

# Set PYTHONPATH to /app so that `import backend.main` works
ENV PYTHONPATH=/app

ENV PORT=8000
EXPOSE 8000

CMD uvicorn backend.main:app --host 0.0.0.0 --port ${PORT}
